CREATE TABLE IF NOT EXISTS PRODUCTS (
    UUID UUID PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL UNIQUE,
    PRODUCT_DESC VARCHAR(1000),
    RETAIL_PRICE NUMERIC(7,2) CHECK ( RETAIL_PRICE > 0 ),
    VENDOR_PRICE NUMERIC(7,2) CHECK ( VENDOR_PRICE > 0 AND VENDOR_PRICE < PRODUCTS.RETAIL_PRICE )

);
