-- ============================================================
-- ENUMS
-- Native Postgres enum types for status fields.
-- More self-documenting than CHAR(1) CHECK constraints,
-- enforced at the type system level, and visible in \d+ output.
-- ============================================================

CREATE TYPE supplier_status    AS ENUM ('active', 'inactive', 'suspended');
CREATE TYPE credential_status  AS ENUM ('active', 'inactive', 'suspended');


-- ============================================================
-- SUPPLIERS
-- Represents companies that supply products through the catalog.
-- A supplier must be active to have product managers assigned.
-- That rule is enforced in the application layer (primary) and
-- via a trigger (backstop) -- see trg_enforce_active_supplier below.
-- ============================================================

CREATE TABLE IF NOT EXISTS SUPPLIERS (
    SUPP_ID      UUID             PRIMARY KEY DEFAULT gen_random_uuid(),
    SUPP_NAME    VARCHAR(255)     NOT NULL UNIQUE,
    SUPP_ADDRESS VARCHAR(255)     NOT NULL,
    STATUS       supplier_status  NOT NULL DEFAULT 'active',
    CREATED_AT   TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMPTZ      NOT NULL DEFAULT NOW()
    );

COMMENT ON TABLE  SUPPLIERS              IS 'Companies that supply products through the catalog.';
COMMENT ON COLUMN SUPPLIERS.SUPP_ID      IS 'Surrogate PK. UUIDv4 generated by DB; never supplied by application.';
COMMENT ON COLUMN SUPPLIERS.SUPP_NAME    IS 'Legal or trading name of the supplier. Unique across all suppliers.';
COMMENT ON COLUMN SUPPLIERS.SUPP_ADDRESS IS 'Primary mailing address for the supplier.';
COMMENT ON COLUMN SUPPLIERS.STATUS       IS 'active=can assign PMs, inactive=no new PMs, suspended=full hold.';
COMMENT ON COLUMN SUPPLIERS.CREATED_AT   IS 'Row creation timestamp (UTC). Set once by DB default; never updated.';
COMMENT ON COLUMN SUPPLIERS.UPDATED_AT   IS 'Last modification timestamp (UTC). Maintained by set_updated_at trigger.';


-- ============================================================
-- PRODUCT MANAGERS
-- Employees of a supplier who own and manage product listings.
-- A PM belongs to exactly one supplier (SUPP_ID NOT NULL).
--
-- IS_ACTIVE state is kept in sync with CREDENTIALS.STATUS
-- via trg_pm_deactivate_credential (see below).
-- ============================================================

CREATE TABLE IF NOT EXISTS PRODUCT_MANAGERS (
    PM_ID      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    SUPP_ID    UUID         NOT NULL REFERENCES SUPPLIERS(SUPP_ID) ON DELETE RESTRICT,
    PM_NAME    VARCHAR(100) NOT NULL,
    PM_EMAIL   VARCHAR(320) NOT NULL UNIQUE,   -- RFC 5321 max; UNIQUE enforces one account per email
    IS_ACTIVE  BOOLEAN      NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    );

CREATE INDEX idx_pm_supp_id  ON PRODUCT_MANAGERS(SUPP_ID);
CREATE INDEX idx_pm_email    ON PRODUCT_MANAGERS(PM_EMAIL);  -- login lookups hit this constantly

COMMENT ON TABLE  PRODUCT_MANAGERS             IS 'Supplier employees who create and manage product listings.';
COMMENT ON COLUMN PRODUCT_MANAGERS.PM_ID       IS 'Surrogate PK.';
COMMENT ON COLUMN PRODUCT_MANAGERS.SUPP_ID     IS 'FK to SUPPLIERS. A PM belongs to exactly one supplier.';
COMMENT ON COLUMN PRODUCT_MANAGERS.PM_NAME     IS 'Full display name of the product manager.';
COMMENT ON COLUMN PRODUCT_MANAGERS.PM_EMAIL    IS 'Login email. Globally unique across all PMs.';
COMMENT ON COLUMN PRODUCT_MANAGERS.IS_ACTIVE   IS 'False disables login; cascades to CREDENTIALS.STATUS via trigger.';
COMMENT ON COLUMN PRODUCT_MANAGERS.CREATED_AT  IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN PRODUCT_MANAGERS.UPDATED_AT  IS 'Last modification timestamp (UTC). Maintained by trigger.';


-- ============================================================
-- PRODUCTS
-- A product is owned by the PM who manages it.
-- Supplier is derived through PM → SUPP_ID, not stored here.
--
-- Price invariant: VENDOR_PRICE must be less than RETAIL_PRICE
-- at all times. The CHECK fires on both INSERT and UPDATE.
--
-- NOTE: lowering RETAIL_PRICE below VENDOR_PRICE on UPDATE is
-- caught by the same CHECK -- Postgres re-evaluates on every
-- write, so no separate trigger is needed for this invariant.
-- ============================================================

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PROD_ID      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    PM_ID        UUID          NOT NULL REFERENCES PRODUCT_MANAGERS(PM_ID) ON DELETE RESTRICT,
    SKU          VARCHAR(100)  NOT NULL UNIQUE,
    PROD_NAME    VARCHAR(255)  NOT NULL,
    PROD_DESC    TEXT,
    RETAIL_PRICE NUMERIC(12,2) NOT NULL CHECK (RETAIL_PRICE > 0),
    VENDOR_PRICE NUMERIC(12,2) NOT NULL CHECK (VENDOR_PRICE > 0),
    IS_PUBLISHED BOOLEAN       NOT NULL DEFAULT FALSE,
    DELETED_AT   TIMESTAMPTZ,                              -- soft delete; NULL = live row
    CREATED_AT   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    UPDATED_AT   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    -- Price integrity: enforced at DB level on every write (INSERT + UPDATE).
    -- Application layer should validate this too for a clean user-facing error,
    -- but the DB constraint is the authoritative backstop.
    CONSTRAINT chk_vendor_lt_retail CHECK (VENDOR_PRICE < RETAIL_PRICE)
    );

CREATE INDEX idx_products_pm_id     ON PRODUCTS(PM_ID);
CREATE INDEX idx_products_prod_name ON PRODUCTS(PROD_NAME);  -- catalog search
CREATE INDEX idx_products_published ON PRODUCTS(IS_PUBLISHED) WHERE IS_PUBLISHED = TRUE;  -- hot read path
CREATE INDEX idx_products_live      ON PRODUCTS(DELETED_AT)   WHERE DELETED_AT IS NULL;   -- exclude soft-deleted rows

COMMENT ON TABLE  PRODUCTS               IS 'Catalog products owned by a product manager.';
COMMENT ON COLUMN PRODUCTS.PROD_ID       IS 'Surrogate PK.';
COMMENT ON COLUMN PRODUCTS.PM_ID         IS 'FK to PRODUCT_MANAGERS. Supplier is derived via PM.SUPP_ID.';
COMMENT ON COLUMN PRODUCTS.SKU           IS 'Stock-keeping unit. Natural business key; globally unique.';
COMMENT ON COLUMN PRODUCTS.PROD_NAME     IS 'Human-readable product title shown in catalog.';
COMMENT ON COLUMN PRODUCTS.PROD_DESC     IS 'Full product description. Optional; may contain markdown.';
COMMENT ON COLUMN PRODUCTS.RETAIL_PRICE  IS 'Customer-facing price in USD. Must exceed VENDOR_PRICE.';
COMMENT ON COLUMN PRODUCTS.VENDOR_PRICE  IS 'Cost to the platform per unit. Must be less than RETAIL_PRICE.';
COMMENT ON COLUMN PRODUCTS.IS_PUBLISHED  IS 'Controls catalog visibility. Defaults to draft (false).';
COMMENT ON COLUMN PRODUCTS.DELETED_AT    IS 'Soft-delete timestamp. NULL means the row is live.';
COMMENT ON COLUMN PRODUCTS.CREATED_AT    IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN PRODUCTS.UPDATED_AT    IS 'Last modification timestamp (UTC). Maintained by trigger.';


-- ============================================================
-- CREDENTIALS
-- Auth data for PMs. Isolated from PRODUCT_MANAGERS so
-- sensitive fields can be permissioned and audited separately.
--
-- Token storage approach:
--   - PASS_HASH:          bcrypt or argon2 hash of the password.
--   - TOKEN_HASH:         SHA-256 hex of the current session token.
--                         SHA-256 is acceptable here because session
--                         tokens are high-entropy (>=128 bits) and
--                         randomly generated -- brute-forcing a
--                         SHA-256 of a random 256-bit token is not
--                         feasible. This is distinct from hashing a
--                         user-chosen password. If policy requires it,
--                         replace with a KDF hash.
--   - REFRESH_TOKEN_HASH: Same approach as TOKEN_HASH.
--   - REFRESH_EXPIRES:    Must be set whenever REFRESH_TOKEN_HASH is
--                         set (enforced by chk_refresh_expiry_paired).
--
-- FAILED_ATTEMPTS:
--   Incremented on each failed login attempt by the application.
--   Reset to 0 on successful authentication by the application.
--   LOCKED_UNTIL is set by the application when threshold is reached.
-- ============================================================

CREATE TABLE IF NOT EXISTS CREDENTIALS (
                                           CRED_ID            UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
    PM_ID              UUID              NOT NULL UNIQUE REFERENCES PRODUCT_MANAGERS(PM_ID) ON DELETE CASCADE,
    PASS_HASH          TEXT              NOT NULL,
    TOKEN_HASH         TEXT,             -- NULL when logged out
    REFRESH_TOKEN_HASH TEXT,             -- NULL when no refresh token issued
    REFRESH_EXPIRES    TIMESTAMPTZ,      -- NULL when no refresh token issued; must be set together with REFRESH_TOKEN_HASH
    STATUS             credential_status NOT NULL DEFAULT 'active',
    FAILED_ATTEMPTS    SMALLINT          NOT NULL DEFAULT 0 CHECK (FAILED_ATTEMPTS >= 0),
    LOCKED_UNTIL       TIMESTAMPTZ,
    CREATED_AT         TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMPTZ       NOT NULL DEFAULT NOW(),

    -- Enforce that REFRESH_EXPIRES is always set when a refresh token exists.
    -- A refresh token without an expiry is effectively non-expiring -- never allow this.
    CONSTRAINT chk_refresh_expiry_paired
    CHECK (REFRESH_TOKEN_HASH IS NULL OR REFRESH_EXPIRES IS NOT NULL)
    );

CREATE INDEX idx_credentials_status ON CREDENTIALS(STATUS);  -- admin queries on locked/suspended accounts

COMMENT ON TABLE  CREDENTIALS                    IS 'Authentication credentials for product managers. Permissioned separately from PRODUCT_MANAGERS.';
COMMENT ON COLUMN CREDENTIALS.CRED_ID            IS 'Surrogate PK.';
COMMENT ON COLUMN CREDENTIALS.PM_ID              IS 'FK to PRODUCT_MANAGERS. 1:1 relationship enforced by UNIQUE.';
COMMENT ON COLUMN CREDENTIALS.PASS_HASH          IS 'bcrypt (~60 chars) or argon2 (~95 chars) hash of the password.';
COMMENT ON COLUMN CREDENTIALS.TOKEN_HASH         IS 'SHA-256 hex of the active session token. NULL when logged out.';
COMMENT ON COLUMN CREDENTIALS.REFRESH_TOKEN_HASH IS 'SHA-256 hex of the long-lived refresh token. NULL if not issued.';
COMMENT ON COLUMN CREDENTIALS.REFRESH_EXPIRES    IS 'Expiry of the refresh token. Must be non-null when REFRESH_TOKEN_HASH is set (enforced by constraint).';
COMMENT ON COLUMN CREDENTIALS.STATUS             IS 'active=can login, inactive=soft-disabled, suspended=admin hold.';
COMMENT ON COLUMN CREDENTIALS.FAILED_ATTEMPTS    IS 'Consecutive failed login attempts. Reset to 0 on success by app.';
COMMENT ON COLUMN CREDENTIALS.LOCKED_UNTIL       IS 'Account locked until this timestamp. NULL when not locked.';
COMMENT ON COLUMN CREDENTIALS.CREATED_AT         IS 'Row creation timestamp (UTC).';
COMMENT ON COLUMN CREDENTIALS.UPDATED_AT         IS 'Last modification timestamp (UTC). Maintained by trigger.';


-- ============================================================
-- UPDATED_AT TRIGGER
-- Automatically keeps UPDATED_AT current on any row change.
-- One function, applied to all four tables.
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_suppliers_updated_at
    BEFORE UPDATE ON SUPPLIERS
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_pm_updated_at
    BEFORE UPDATE ON PRODUCT_MANAGERS
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON PRODUCTS
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_credentials_updated_at
    BEFORE UPDATE ON CREDENTIALS
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ============================================================
-- SUPPLIER ACTIVE GUARD (backstop trigger)
-- Prevents assigning a PM to a non-active supplier.
-- Primary enforcement is in the application layer.
-- This trigger fires on INSERT and on SUPP_ID reassignment (UPDATE)
-- as a hard backstop for direct DB writes, scripts, and migrations.
-- ============================================================

CREATE OR REPLACE FUNCTION enforce_active_supplier()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT STATUS FROM SUPPLIERS WHERE SUPP_ID = NEW.SUPP_ID) <> 'active' THEN
        RAISE EXCEPTION 'Cannot assign PM to a non-active supplier (SUPP_ID: %)', NEW.SUPP_ID;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_enforce_active_supplier
    BEFORE INSERT OR UPDATE OF SUPP_ID ON PRODUCT_MANAGERS
    FOR EACH ROW EXECUTE FUNCTION enforce_active_supplier();


-- ============================================================
-- PM DEACTIVATION CASCADE
-- When a PM is set IS_ACTIVE = FALSE, their credential STATUS
-- is automatically set to 'inactive', invalidating active sessions.
-- Without this, a deactivated PM could still authenticate.
-- ============================================================

CREATE OR REPLACE FUNCTION sync_credential_on_pm_deactivate()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.IS_ACTIVE = TRUE AND NEW.IS_ACTIVE = FALSE THEN
UPDATE CREDENTIALS
SET    STATUS     = 'inactive',
       TOKEN_HASH = NULL   -- invalidate active session immediately
WHERE  PM_ID = NEW.PM_ID;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pm_deactivate_credential
    AFTER UPDATE OF IS_ACTIVE ON PRODUCT_MANAGERS
    FOR EACH ROW EXECUTE FUNCTION sync_credential_on_pm_deactivate();


-- ============================================================
-- AUDIT LOG
-- Append-only record of all data-mutating events across the
-- four core tables. Captures who changed what and when.
--
-- actor_pm_id is the PM performing the action (NULL for system
-- or migration-originated changes).
--
-- old_data / new_data store the full row as JSONB so point-in-time
-- reconstruction is possible without a separate column per field.
--
-- This table should have INSERT-only grants for the app role;
-- no UPDATE or DELETE should ever be permitted.
-- ============================================================

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
                                         LOG_ID       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    TABLE_NAME   VARCHAR(50) NOT NULL,
    RECORD_ID    UUID        NOT NULL,
    OPERATION    CHAR(1)     NOT NULL CHECK (OPERATION IN ('I', 'U', 'D')),  -- Insert / Update / Delete
    ACTOR_PM_ID  UUID        REFERENCES PRODUCT_MANAGERS(PM_ID) ON DELETE SET NULL,
    OLD_DATA     JSONB,
    NEW_DATA     JSONB,
    CHANGED_AT   TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

CREATE INDEX idx_audit_table_record ON AUDIT_LOG(TABLE_NAME, RECORD_ID);
CREATE INDEX idx_audit_changed_at   ON AUDIT_LOG(CHANGED_AT DESC);
CREATE INDEX idx_audit_actor        ON AUDIT_LOG(ACTOR_PM_ID) WHERE ACTOR_PM_ID IS NOT NULL;

COMMENT ON TABLE  AUDIT_LOG             IS 'Append-only audit trail for all mutations to core tables.';
COMMENT ON COLUMN AUDIT_LOG.LOG_ID      IS 'Surrogate PK.';
COMMENT ON COLUMN AUDIT_LOG.TABLE_NAME  IS 'Name of the table that was mutated.';
COMMENT ON COLUMN AUDIT_LOG.RECORD_ID   IS 'PK of the mutated row in TABLE_NAME.';
COMMENT ON COLUMN AUDIT_LOG.OPERATION   IS 'I=insert, U=update, D=delete.';
COMMENT ON COLUMN AUDIT_LOG.ACTOR_PM_ID IS 'PM who performed the action. NULL for system/migration changes.';
COMMENT ON COLUMN AUDIT_LOG.OLD_DATA    IS 'Full row state before the mutation (NULL for inserts).';
COMMENT ON COLUMN AUDIT_LOG.NEW_DATA    IS 'Full row state after the mutation (NULL for deletes).';
COMMENT ON COLUMN AUDIT_LOG.CHANGED_AT  IS 'Timestamp of the mutation (UTC).';


-- ============================================================
-- NOTES FOR PRODUCTION READINESS
-- These items are architectural decisions that belong in
-- runbooks or ADRs rather than DDL, documented here for
-- visibility during review.
--
-- 1. UUID STRATEGY
--    gen_random_uuid() produces UUIDv4 (random), which causes
--    B-tree index fragmentation at high insert rates. Consider
--    migrating to UUIDv7 (time-ordered) or ULIDs for tables
--    with heavy write volume (PRODUCTS, AUDIT_LOG especially).
--    A custom gen_uuidv7() function can be added via pgcrypto.
--
-- 2. ROW-LEVEL SECURITY (RLS)
--    In a multi-tenant deployment, enable RLS on PRODUCTS and
--    PRODUCT_MANAGERS so supplier A's app role cannot read or
--    write supplier B's rows. Policy skeleton:
--        ALTER TABLE PRODUCTS ENABLE ROW LEVEL SECURITY;
--        CREATE POLICY supplier_isolation ON PRODUCTS
--            USING (PM_ID IN (
--                SELECT PM_ID FROM PRODUCT_MANAGERS
--                WHERE SUPP_ID = current_setting('app.current_supp_id')::UUID
--            ));
--
-- 3. TOKEN EXPIRY / ARCHIVAL
--    TOKEN_HASH and REFRESH_TOKEN_HASH have no built-in TTL.
--    A nightly job should NULL out TOKEN_HASH rows where
--    LOCKED_UNTIL < NOW() and REFRESH_TOKEN_HASH rows where
--    REFRESH_EXPIRES < NOW(). Consider pg_cron for this.
--
-- 4. FAILED_ATTEMPTS RESET
--    Application must reset FAILED_ATTEMPTS = 0 and
--    LOCKED_UNTIL = NULL on every successful authentication.
--    The DB has no way to know what "successful" means without
--    application context, so this is intentionally app-layer only.
--
-- 5. PARTITIONING
--    AUDIT_LOG will grow unboundedly. Partition by CHANGED_AT
--    (range, monthly) once row count exceeds ~10M. PRODUCTS
--    may benefit from range partitioning by CREATED_AT if the
--    catalog grows into the tens of millions.
--
-- 6. READ REPLICA ROUTING
--    The IS_PUBLISHED partial index targets the hot catalog read
--    path. Route all IS_PUBLISHED = TRUE queries to read replicas
--    in the application layer. Write path (publish/unpublish) stays
--    on primary.
-- ============================================================