/**
 * Project: JDBCTemplate Practice
 * Description: A repository implementation that handles crud operations on the product domain using JDBCTemplate and
 *              raw sql instead of an orm.
 * Author: Benjamin Soto-Roberts
 * Created: 03/03/2026
 */

package JDBCTemplatePractice.persistence;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;
import JDBCTemplatePractice.exception.ProductNotFoundException;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;

@Repository
public class ProductRepository {

    // -- Data Field --
    private final JdbcTemplate jdbcTemplate;
    private static final RowMapper<Product> PRODUCT_ROW_MAPPER = new ProductRowMapper(); // Stateless, reusable

    // -- Constructors --
    @Autowired
    public ProductRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    // -- Inner Class -- Custom row mapper class to map database data to Product POJO
    private static final class ProductRowMapper implements RowMapper<Product> {

        /**
         * Maps the row data from the result set to product by field name
         * */
        @Override
        public Product mapRow(ResultSet rs, int rowNum) throws SQLException {
            Product product = new Product();
            product.setUuid(rs.getObject("UUID", UUID.class));
            product.setProductName(rs.getString("PRODUCT_NAME"));
            product.setProductDesc(rs.getString("PRODUCT_DESC"));
            product.setRetailPrice(rs.getBigDecimal("RETAIL_PRICE"));
            product.setVendorPrice(rs.getBigDecimal("VENDOR_PRICE"));
            return product;
        }
    }


    /**
     * Returns a list of products from the product table through select all statement. Uses the ProductRowMapper to map
     * the rows and contents to the product list.
     * */
    public List<Product> getAllProducts() {
        String sql = "SELECT * FROM PRODUCTS";
        return jdbcTemplate.query(sql, PRODUCT_ROW_MAPPER);
    }

    /**
     * Returns a single product from the product table through a select statement targeting a specific uuid. Uses the
     * ProductRowMapper to map the row contents to the product. Catches EmptyResultDataAccessException if queryForObject
     * throws exception and throws ProductNotFoundException that propagates up the call stack
     * */
    public Product getProductById(UUID uuid) {
        String sql = "SELECT * FROM PRODUCTS WHERE UUID = ?";

        try {
            return jdbcTemplate.queryForObject(sql, PRODUCT_ROW_MAPPER, uuid);
        } catch (EmptyResultDataAccessException ex) {
            throw new ProductNotFoundException("Product not found: " + uuid);
        }
    }

    /**
     * Saves a product to the product table through insert statement and returns the product using getProductById.
     * Assumes UUID is already set on product, not generated by db
     * */
    public Product saveProduct(Product product) {
        String sql = "INSERT INTO PRODUCTS (UUID, PRODUCT_NAME, PRODUCT_DESC, RETAIL_PRICE, VENDOR_PRICE) VALUES (?, ?, ?, ?, ?)";

        jdbcTemplate.update(sql,
                product.getUuid(),
                product.getProductName(),
                product.getProductDesc(),
                product.getRetailPrice(),
                product.getVendorPrice());

        return getProductById(product.getUuid());
    }

    /**
     * Updates an existing product to the product table through update statement and returns the product using
     * getProductById. No rows affected is treated as the not found condition. If no product was found a custom
     * exception is thrown to propagate up the call stack
     * */
    public Product updateProduct(Product product) {
        String sql = "UPDATE PRODUCTS SET PRODUCT_NAME = ?, PRODUCT_DESC = ?, RETAIL_PRICE = ?, VENDOR_PRICE = ? WHERE UUID = ?";

        int rows = jdbcTemplate.update(sql,
                product.getProductName(),
                product.getProductDesc(),
                product.getRetailPrice(),
                product.getVendorPrice(),
                product.getUuid());

        // no rows updated = product not found
        if (rows == 0) {
            throw new ProductNotFoundException("Product not found: " + product.getUuid());
        }

        return getProductById(product.getUuid());

    }

    /**
     * Deletes an existing product from the product table through delete statement, returns void for successful
     * deletion. No rows affected is treated as the not found condition. If no product was found a custom exception is
     * thrown to propagate up the call stack
     * */
    public void deleteProductById(UUID uuid) {
        String sql = "DELETE FROM PRODUCTS WHERE UUID = ?";
        int rows = jdbcTemplate.update(sql, uuid);

        // no rows updated = product not found
        if (rows == 0) {
            throw new ProductNotFoundException("Product not found: " + uuid);
        }

    }

}
